#!/bin/sh
CFLAGS="-ggdb -Os --std=gnu99 -Wall -Wextra -Wno-missing-field-initializers -Wno-unused-parameter -DPLATFORM_STRING=\"${PLATFORM_STRING}\""
LDFLAGS="-llua-socket -llua-filesystem -llua-md5 -llua-yajl -llua-ev -lev -lyajl -lsha2 -lmodpbase64"
