#!/bin/sh
target=$1; shift
./quiet "$target" "toolchains/$BASEARCH"/compile-c -o "$target" \
  -ggdb -Os --std=gnu99 -Wall -Wextra -Wno-missing-field-initializers -Wno-unused-parameter \
  -I"toolchains/$BASEARCH"/lib -include "toolchains/$BASEARCH"/platform.h \
  "$@"
