#!/bin/zsh

targets=(linux{,64,-arm64,-armhf,-armv5} linux{64,-arm64}-musl osx win{32,64} openwrt{-mips,-mipsel})
targets=(pkg/${^targets}{,-jit})

disabled=(pkg/win32-jit pkg/win64-jit)

make ${targets:|disabled}

DATE=$(date +%Y.%m.%d)
DIR=thb-$DATE

mkdir -p $DIR
mv install/thb-*$DATE* $DIR/
rsync -avP $DIR loee:srv/thb/dl/

git tag -a "$DIR" -m "Release $DATE"
git push --tags

echo
echo "http://thb.loee.pl/dl/$DIR"
echo
