#!/bin/sh

make pkg/linux pkg/linux64 pkg/osx64 pkg/osx \
     pkg/linux-armhf pkg/win32 pkg/win64 pkg/openwrt-mips-uClibc
#./remote jpc@green openwrt-mips pkg
#./remote jpc@green openwrt-mips-uClibc pkg

DATE=$(date +%Y.%m.%d)
DIR=thb-$DATE

mkdir -p $DIR
mv install/thb-*$DATE* $DIR/
rsync -avP $DIR loee:srv/thb/dl/

git tag -a "$DIR" -m "Release $DATE"
git push --tags
