return setmetatable({
-- from /System/Library/Frameworks/IOKit.framework/Headers/IOReturn.h
            ["iokit/Error"] = 0xe00002bc, -- general error
         ["iokit/NoMemory"] = 0xe00002bd, -- can't allocate memory
      ["iokit/NoResources"] = 0xe00002be, -- resource shortage
         ["iokit/IPCError"] = 0xe00002bf, -- error during IPC
         ["iokit/NoDevice"] = 0xe00002c0, -- no such device
    ["iokit/NotPrivileged"] = 0xe00002c1, -- privilege violation
      ["iokit/BadArgument"] = 0xe00002c2, -- invalid argument
       ["iokit/LockedRead"] = 0xe00002c3, -- device read locked
      ["iokit/LockedWrite"] = 0xe00002c4, -- device write locked
  ["iokit/ExclusiveAccess"] = 0xe00002c5, -- exclusive access and device already open
     ["iokit/BadMessageID"] = 0xe00002c6, -- sent/received messages had different msg_id
      ["iokit/Unsupported"] = 0xe00002c7, -- unsupported function
          ["iokit/VMError"] = 0xe00002c8, -- misc. VM failure
    ["iokit/InternalError"] = 0xe00002c9, -- internal error
          ["iokit/IOError"] = 0xe00002ca, -- General I/O error
       ["iokit/CannotLock"] = 0xe00002cc, -- can't acquire lock
          ["iokit/NotOpen"] = 0xe00002cd, -- device not open
      ["iokit/NotReadable"] = 0xe00002ce, -- read not supported
      ["iokit/NotWritable"] = 0xe00002cf, -- write not supported
       ["iokit/NotAligned"] = 0xe00002d0, -- alignment error
         ["iokit/BadMedia"] = 0xe00002d1, -- Media Error
        ["iokit/StillOpen"] = 0xe00002d2, -- device(s) still open
         ["iokit/RLDError"] = 0xe00002d3, -- rld failure
         ["iokit/DMAError"] = 0xe00002d4, -- DMA failure
             ["iokit/Busy"] = 0xe00002d5, -- Device Busy
          ["iokit/Timeout"] = 0xe00002d6, -- I/O Timeout
          ["iokit/Offline"] = 0xe00002d7, -- device offline
         ["iokit/NotReady"] = 0xe00002d8, -- not ready
      ["iokit/NotAttached"] = 0xe00002d9, -- device not attached
       ["iokit/NoChannels"] = 0xe00002da, -- no DMA channels left
          ["iokit/NoSpace"] = 0xe00002db, -- no space for data
       ["iokit/PortExists"] = 0xe00002dd, -- port already exists
       ["iokit/CannotWire"] = 0xe00002de, -- can't wire down physical memory
      ["iokit/NoInterrupt"] = 0xe00002df, -- no interrupt attached
         ["iokit/NoFrames"] = 0xe00002e0, -- no DMA frames enqueued
  ["iokit/MessageTooLarge"] = 0xe00002e1, -- oversized msg received on interrupt port
     ["iokit/NotPermitted"] = 0xe00002e2, -- not permitted
          ["iokit/NoPower"] = 0xe00002e3, -- no power to device
          ["iokit/NoMedia"] = 0xe00002e4, -- media not present
 ["iokit/UnformattedMedia"] = 0xe00002e5, -- media not formatted
  ["iokit/UnsupportedMode"] = 0xe00002e6, -- no such mode
         ["iokit/Underrun"] = 0xe00002e7, -- data underrun
          ["iokit/Overrun"] = 0xe00002e8, -- data overrun
      ["iokit/DeviceError"] = 0xe00002e9, -- the device is not working properly!
     ["iokit/NoCompletion"] = 0xe00002ea, -- a completion routine is required
          ["iokit/Aborted"] = 0xe00002eb, -- operation aborted
      ["iokit/NoBandwidth"] = 0xe00002ec, -- bus bandwidth would be exceeded
    ["iokit/NotResponding"] = 0xe00002ed, -- device not responding
        ["iokit/IsoTooOld"] = 0xe00002ee, -- isochronous I/O request for distant past!
        ["iokit/IsoTooNew"] = 0xe00002ef, -- isochronous I/O request for distant future
         ["iokit/NotFound"] = 0xe00002f0, -- data was not found
          ["iokit/Invalid"] = 0xe0000001, -- should never be seen
               [0xe00002bc] = "iokit/Error",
               [0xe00002bd] = "iokit/NoMemory",
               [0xe00002be] = "iokit/NoResources",
               [0xe00002bf] = "iokit/IPCError",
               [0xe00002c0] = "iokit/NoDevice",
               [0xe00002c1] = "iokit/NotPrivileged",
               [0xe00002c2] = "iokit/BadArgument",
               [0xe00002c3] = "iokit/LockedRead",
               [0xe00002c4] = "iokit/LockedWrite",
               [0xe00002c5] = "iokit/ExclusiveAccess",
               [0xe00002c6] = "iokit/BadMessageID",
               [0xe00002c7] = "iokit/Unsupported",
               [0xe00002c8] = "iokit/VMError",
               [0xe00002c9] = "iokit/InternalError",
               [0xe00002ca] = "iokit/IOError",
               [0xe00002cc] = "iokit/CannotLock",
               [0xe00002cd] = "iokit/NotOpen",
               [0xe00002ce] = "iokit/NotReadable",
               [0xe00002cf] = "iokit/NotWritable",
               [0xe00002d0] = "iokit/NotAligned",
               [0xe00002d1] = "iokit/BadMedia",
               [0xe00002d2] = "iokit/StillOpen",
               [0xe00002d3] = "iokit/RLDError",
               [0xe00002d4] = "iokit/DMAError",
               [0xe00002d5] = "iokit/Busy",
               [0xe00002d6] = "iokit/Timeout",
               [0xe00002d7] = "iokit/Offline",
               [0xe00002d8] = "iokit/NotReady",
               [0xe00002d9] = "iokit/NotAttached",
               [0xe00002da] = "iokit/NoChannels",
               [0xe00002db] = "iokit/NoSpace",
               [0xe00002dd] = "iokit/PortExists",
               [0xe00002de] = "iokit/CannotWire",
               [0xe00002df] = "iokit/NoInterrupt",
               [0xe00002e0] = "iokit/NoFrames",
               [0xe00002e1] = "iokit/MessageTooLarge",
               [0xe00002e2] = "iokit/NotPermitted",
               [0xe00002e3] = "iokit/NoPower",
               [0xe00002e4] = "iokit/NoMedia",
               [0xe00002e5] = "iokit/UnformattedMedia",
               [0xe00002e6] = "iokit/UnsupportedMode",
               [0xe00002e7] = "iokit/Underrun",
               [0xe00002e8] = "iokit/Overrun",
               [0xe00002e9] = "iokit/DeviceError",
               [0xe00002ea] = "iokit/NoCompletion",
               [0xe00002eb] = "iokit/Aborted",
               [0xe00002ec] = "iokit/NoBandwidth",
               [0xe00002ed] = "iokit/NotResponding",
               [0xe00002ee] = "iokit/IsoTooOld",
               [0xe00002ef] = "iokit/IsoTooNew",
               [0xe00002f0] = "iokit/NotFound",
               [0xe0000001] = "iokit/Invalid",

-- from /System/Library/Frameworks/IOKit.framework/Headers/usb/USB.h
                             ["iokit/usb/UnknownPipeErr"] = 0xe0004061, -- Pipe ref not recognized
                            ["iokit/usb/TooManyPipesErr"] = 0xe0004060, -- Too many pipes
                             ["iokit/usb/NoAsyncPortErr"] = 0xe000405f, -- no async port
                          ["iokit/usb/NotEnoughPipesErr"] = 0xe000405e, -- not enough pipes in interface
                          ["iokit/usb/NotEnoughPowerErr"] = 0xe000405d, -- not enough power for selected configuration
                           ["iokit/usb/EndpointNotFound"] = 0xe0004057, -- Endpoint Not found
                             ["iokit/usb/ConfigNotFound"] = 0xe0004056, -- Configuration Not found
                         ["iokit/usb/TransactionTimeout"] = 0xe0004051, -- Transaction timed out
                        ["iokit/usb/TransactionReturned"] = 0xe0004050, -- The transaction has been returned to the caller
                                ["iokit/usb/PipeStalled"] = 0xe000404f, -- Pipe has stalled, error needs to be cleared
                          ["iokit/usb/InterfaceNotFound"] = 0xe000404e, -- Interface ref not recognized
     ["iokit/usb/LowLatencyBufferNotPreviouslyAllocated"] = 0xe000404d, -- Attempted to use user land low latency isoc calls w/out calling PrepareBuffer (on the data buffer) first 
  ["iokit/usb/LowLatencyFrameListNotPreviouslyAllocated"] = 0xe000404c, -- Attempted to use user land low latency isoc calls w/out calling PrepareBuffer (on the frame list) first
                        ["iokit/usb/HighSpeedSplitError"] = 0xe000404b, -- Error to hub on high speed bus trying to do split transaction
                      ["iokit/usb/SyncRequestOnWLThread"] = 0xe000404a, -- A synchronous USB request was made on the workloop thread (from a callback?).  Only async requests are permitted in that case
                         ["iokit/usb/DeviceNotHighSpeed"] = 0xe0004049, -- Name is deprecated, see below
               ["iokit/usb/DeviceTransferredToCompanion"] = 0xe0004049, -- The device has been tranferred to another controller for enumeration
                 ["iokit/usb/ClearPipeStallNotRecursive"] = 0xe0004048, -- IOUSBPipe::ClearPipeStall should not be called recursively
                  ["iokit/usb/DevicePortWasNotSuspended"] = 0xe0004047, -- Port was not suspended
                      ["iokit/usb/EndpointCountExceeded"] = 0xe0004046, -- The endpoint was not created because the controller cannot support more endpoints
                        ["iokit/usb/DeviceCountExceeded"] = 0xe0004045, -- The device cannot be enumerated because the controller cannot support more devices
                        ["iokit/usb/StreamsNotSupported"] = 0xe0004044, -- The request cannot be completed because the XHCI controller does not support streams
                                             [0xe0004061] = "iokit/usb/UnknownPipeErr",
                                             [0xe0004060] = "iokit/usb/TooManyPipesErr",
                                             [0xe000405f] = "iokit/usb/NoAsyncPortErr",
                                             [0xe000405e] = "iokit/usb/NotEnoughPipesErr",
                                             [0xe000405d] = "iokit/usb/NotEnoughPowerErr",
                                             [0xe0004057] = "iokit/usb/EndpointNotFound",
                                             [0xe0004056] = "iokit/usb/ConfigNotFound",
                                             [0xe0004051] = "iokit/usb/TransactionTimeout",
                                             [0xe0004050] = "iokit/usb/TransactionReturned",
                                             [0xe000404f] = "iokit/usb/PipeStalled",
                                             [0xe000404e] = "iokit/usb/InterfaceNotFound",
                                             [0xe000404d] = "iokit/usb/LowLatencyBufferNotPreviouslyAllocated",
                                             [0xe000404c] = "iokit/usb/LowLatencyFrameListNotPreviouslyAllocated",
                                             [0xe000404b] = "iokit/usb/HighSpeedSplitError",
                                             [0xe000404a] = "iokit/usb/SyncRequestOnWLThread",
                                             [0xe0004049] = "iokit/usb/DeviceNotHighSpeed",
                                             [0xe0004049] = "iokit/usb/DeviceTransferredToCompanion",
                                             [0xe0004048] = "iokit/usb/ClearPipeStallNotRecursive",
                                             [0xe0004047] = "iokit/usb/DevicePortWasNotSuspended",
                                             [0xe0004046] = "iokit/usb/EndpointCountExceeded",
                                             [0xe0004045] = "iokit/usb/DeviceCountExceeded",
                                             [0xe0004044] = "iokit/usb/StreamsNotSupported",

                                    ["iokit/usb/LinkErr"] = 0xe0004010, --
                                ["iokit/usb/NotSent2Err"] = 0xe000400f, -- Transaction not sent
                                ["iokit/usb/NotSent1Err"] = 0xe000400e, -- Transaction not sent
                          ["iokit/usb/BufferUnderrunErr"] = 0xe000400d, -- Buffer Underrun (Host hardware failure on data out, PCI busy?)
                           ["iokit/usb/BufferOverrunErr"] = 0xe000400c, -- Buffer Overrun (Host hardware failure on data out, PCI busy?)
                               ["iokit/usb/Reserved2Err"] = 0xe000400b, -- Reserved
                               ["iokit/usb/Reserved1Err"] = 0xe000400a, -- Reserved
                                ["iokit/usb/WrongPIDErr"] = 0xe0004007, -- Pipe stall, Bad or wrong PID
                                   ["iokit/usb/CheckErr"] = 0xe0004006, -- Pipe stall, PID CRC error
                              ["iokit/usb/DataToggleErr"] = 0xe0004003, -- Pipe stall, Bad data toggle
                                 ["iokit/usb/BitstufErr"] = 0xe0004002, -- Pipe stall, bitstuffing
                                        ["iokit/usb/Err"] = 0xe0004001, -- Pipe stall, bad CRC
                                             [0xe0004010] = "iokit/usb/LinkErr",
                                             [0xe000400f] = "iokit/usb/NotSent2Err",
                                             [0xe000400e] = "iokit/usb/NotSent1Err",
                                             [0xe000400d] = "iokit/usb/BufferUnderrunErr",
                                             [0xe000400c] = "iokit/usb/BufferOverrunErr",
                                             [0xe000400b] = "iokit/usb/Reserved2Err",
                                             [0xe000400a] = "iokit/usb/Reserved1Err",
                                             [0xe0004007] = "iokit/usb/WrongPIDErr",
                                             [0xe0004006] = "iokit/usb/CheckErr",
                                             [0xe0004003] = "iokit/usb/DataToggleErr",
                                             [0xe0004002] = "iokit/usb/BitstufErr",
                                             [0xe0004001] = "iokit/usb/Err",

-- from /usr/include/sys/errno.h
                  ["EPERM"] = 1,   -- Operation not permitted
                 ["ENOENT"] = 2,   -- No such file or directory
                  ["ESRCH"] = 3,   -- No such process
                  ["EINTR"] = 4,   -- Interrupted system call
                    ["EIO"] = 5,   -- Input/output error
                  ["ENXIO"] = 6,   -- Device not configured
                  ["E2BIG"] = 7,   -- Argument list too long
                ["ENOEXEC"] = 8,   -- Exec format error
                  ["EBADF"] = 9,   -- Bad file descriptor
                 ["ECHILD"] = 10,  -- No child processes
                ["EDEADLK"] = 11,  -- Resource deadlock avoided // 11 was EAGAIN
                 ["ENOMEM"] = 12,  -- Cannot allocate memory
                 ["EACCES"] = 13,  -- Permission denied
                 ["EFAULT"] = 14,  -- Bad address
                ["ENOTBLK"] = 15,  -- Block device required
                  ["EBUSY"] = 16,  -- Device / Resource busy
                 ["EEXIST"] = 17,  -- File exists
                  ["EXDEV"] = 18,  -- Cross-device link
                 ["ENODEV"] = 19,  -- Operation not supported by device
                ["ENOTDIR"] = 20,  -- Not a directory
                 ["EISDIR"] = 21,  -- Is a directory
                 ["EINVAL"] = 22,  -- Invalid argument
                 ["ENFILE"] = 23,  -- Too many open files in system
                 ["EMFILE"] = 24,  -- Too many open files
                 ["ENOTTY"] = 25,  -- Inappropriate ioctl for device
                ["ETXTBSY"] = 26,  -- Text file busy
                  ["EFBIG"] = 27,  -- File too large
                 ["ENOSPC"] = 28,  -- No space left on device
                 ["ESPIPE"] = 29,  -- Illegal seek
                  ["EROFS"] = 30,  -- Read-only file system
                 ["EMLINK"] = 31,  -- Too many links
                  ["EPIPE"] = 32,  -- Broken pipe
                   ["EDOM"] = 33,  -- Numerical argument out of domain
                 ["ERANGE"] = 34,  -- Result too large
                 ["EAGAIN"] = 35,  -- Resource temporarily unavailable
            ["EWOULDBLOCK"] = 35,  -- Operation would block
            ["EINPROGRESS"] = 36,  -- Operation now in progress
               ["EALREADY"] = 37,  -- Operation already in progress
               ["ENOTSOCK"] = 38,  -- Socket operation on non-socket
           ["EDESTADDRREQ"] = 39,  -- Destination address required
               ["EMSGSIZE"] = 40,  -- Message too long
             ["EPROTOTYPE"] = 41,  -- Protocol wrong type for socket
            ["ENOPROTOOPT"] = 42,  -- Protocol not available
                ["ENOTSUP"] = 45,  -- Operation not supported
           ["EPFNOSUPPORT"] = 46,  -- Protocol family not supported
           ["EAFNOSUPPORT"] = 47,  -- Address family not supported by protocol family
             ["EADDRINUSE"] = 48,  -- Address already in use
          ["EADDRNOTAVAIL"] = 49,  -- Can't assign requested address
               ["ENETDOWN"] = 50,  -- Network is down
            ["ENETUNREACH"] = 51,  -- Network is unreachable
              ["ENETRESET"] = 52,  -- Network dropped connection on reset
           ["ECONNABORTED"] = 53,  -- Software caused connection abort
             ["ECONNRESET"] = 54,  -- Connection reset by peer
                ["ENOBUFS"] = 55,  -- No buffer space available
                ["EISCONN"] = 56,  -- Socket is already connected
               ["ENOTCONN"] = 57,  -- Socket is not connected
              ["ESHUTDOWN"] = 58,  -- Can't send after socket shutdown
           ["ETOOMANYREFS"] = 59,  -- Too many references: can't splice
              ["ETIMEDOUT"] = 60,  -- Operation timed out
           ["ECONNREFUSED"] = 61,  -- Connection refused
                  ["ELOOP"] = 62,  -- Too many levels of symbolic links
           ["ENAMETOOLONG"] = 63,  -- File name too long
              ["EHOSTDOWN"] = 64,  -- Host is down
           ["EHOSTUNREACH"] = 65,  -- No route to host
              ["ENOTEMPTY"] = 66,  -- Directory not empty
               ["EPROCLIM"] = 67,  -- Too many processes
                 ["EUSERS"] = 68,  -- Too many users
                 ["EDQUOT"] = 69,  -- Disc quota exceeded
                 ["ESTALE"] = 70,  -- Stale NFS file handle
                ["EREMOTE"] = 71,  -- Too many levels of remote in path
                ["EBADRPC"] = 72,  -- RPC struct is bad
           ["ERPCMISMATCH"] = 73,  -- RPC version wrong
           ["EPROGUNAVAIL"] = 74,  -- RPC prog. not avail
          ["EPROGMISMATCH"] = 75,  -- Program version wrong
           ["EPROCUNAVAIL"] = 76,  -- Bad procedure for program
                 ["ENOLCK"] = 77,  -- No locks available
                 ["ENOSYS"] = 78,  -- Function not implemented
                 ["EFTYPE"] = 79,  -- Inappropriate file type or format
                  ["EAUTH"] = 80,  -- Authentication error
              ["ENEEDAUTH"] = 81,  -- Need authenticator
                ["EPWROFF"] = 82,  -- Device power is off
                ["EDEVERR"] = 83,  -- Device error, e.g. paper out
              ["EOVERFLOW"] = 84,  -- Value too large to be stored in data type
               ["EBADEXEC"] = 85,  -- Bad executable
               ["EBADARCH"] = 86,  -- Bad CPU type in executable
             ["ESHLIBVERS"] = 87,  -- Shared library version mismatch
              ["EBADMACHO"] = 88,  -- Malformed Macho file
              ["ECANCELED"] = 89,  -- Operation canceled
                  ["EIDRM"] = 90,  -- Identifier removed
                 ["ENOMSG"] = 91,  -- No message of desired type
                 ["EILSEQ"] = 92,  -- Illegal byte sequence
                ["ENOATTR"] = 93,  -- Attribute not found
                ["EBADMSG"] = 94,  -- Bad message
              ["EMULTIHOP"] = 95,  -- Reserved
                ["ENODATA"] = 96,  -- No message available on STREAM
                ["ENOLINK"] = 97,  -- Reserved
                  ["ENOSR"] = 98,  -- No STREAM resources
                 ["ENOSTR"] = 99,  -- Not a STREAM
                 ["EPROTO"] = 100, -- Protocol error
                  ["ETIME"] = 101, -- STREAM ioctl timeout
             ["EOPNOTSUPP"] = 102, -- Operation not supported on socket
              ["ENOPOLICY"] = 103, -- No such policy registered
             ["EOWNERDEAD"] = 105, -- Previous owner died
                 ["EQFULL"] = 106, -- Interface output queue is full
                  ["ELAST"] = 106, -- Must be equal largest errno
                        [1] = "EPERM",
                        [2] = "ENOENT",
                        [3] = "ESRCH",
                        [4] = "EINTR",
                        [5] = "EIO",
                        [6] = "ENXIO",
                        [7] = "E2BIG",
                        [8] = "ENOEXEC",
                        [9] = "EBADF",
                       [10] = "ECHILD",
                       [11] = "EDEADLK",
                       [12] = "ENOMEM",
                       [13] = "EACCES",
                       [14] = "EFAULT",
                       [15] = "ENOTBLK",
                       [16] = "EBUSY",
                       [17] = "EEXIST",
                       [18] = "EXDEV",
                       [19] = "ENODEV",
                       [20] = "ENOTDIR",
                       [21] = "EISDIR",
                       [22] = "EINVAL",
                       [23] = "ENFILE",
                       [24] = "EMFILE",
                       [25] = "ENOTTY",
                       [26] = "ETXTBSY",
                       [27] = "EFBIG",
                       [28] = "ENOSPC",
                       [29] = "ESPIPE",
                       [30] = "EROFS",
                       [31] = "EMLINK",
                       [32] = "EPIPE",
                       [33] = "EDOM",
                       [34] = "ERANGE",
                       [35] = "EAGAIN",
                       [36] = "EINPROGRESS",
                       [37] = "EALREADY",
                       [38] = "ENOTSOCK",
                       [39] = "EDESTADDRREQ",
                       [40] = "EMSGSIZE",
                       [41] = "EPROTOTYPE",
                       [42] = "ENOPROTOOPT",
                       [43] = "EPROTONOSUPPORT",
                       [44] = "ESOCKTNOSUPPORT",
                       [45] = "ENOTSUP",
                       [46] = "EPFNOSUPPORT",
                       [47] = "EAFNOSUPPORT",
                       [48] = "EADDRINUSE",
                       [49] = "EADDRNOTAVAIL",
                       [50] = "ENETDOWN",
                       [51] = "ENETUNREACH",
                       [52] = "ENETRESET",
                       [53] = "ECONNABORTED",
                       [54] = "ECONNRESET",
                       [55] = "ENOBUFS",
                       [56] = "EISCONN",
                       [57] = "ENOTCONN",
                       [58] = "ESHUTDOWN",
                       [59] = "ETOOMANYREFS",
                       [60] = "ETIMEDOUT",
                       [61] = "ECONNREFUSED",
                       [62] = "ELOOP",
                       [63] = "ENAMETOOLONG",
                       [64] = "EHOSTDOWN",
                       [65] = "EHOSTUNREACH",
                       [66] = "ENOTEMPTY",
                       [67] = "EPROCLIM",
                       [68] = "EUSERS",
                       [69] = "EDQUOT",
                       [70] = "ESTALE",
                       [71] = "EREMOTE",
                       [72] = "EBADRPC",
                       [73] = "ERPCMISMATCH",
                       [74] = "EPROGUNAVAIL",
                       [75] = "EPROGMISMATCH",
                       [76] = "EPROCUNAVAIL",
                       [77] = "ENOLCK",
                       [78] = "ENOSYS",
                       [79] = "EFTYPE",
                       [80] = "EAUTH",
                       [81] = "ENEEDAUTH",
                       [82] = "EPWROFF",
                       [83] = "EDEVERR",
                       [84] = "EOVERFLOW",
                       [85] = "EBADEXEC",
                       [86] = "EBADARCH",
                       [87] = "ESHLIBVERS",
                       [88] = "EBADMACHO",
                       [89] = "ECANCELED",
                       [90] = "EIDRM",
                       [91] = "ENOMSG",
                       [92] = "EILSEQ",
                       [93] = "ENOATTR",
                       [94] = "EBADMSG",
                       [95] = "EMULTIHOP",
                       [96] = "ENODATA",
                       [97] = "ENOLINK",
                       [98] = "ENOSR",
                       [99] = "ENOSTR",
                      [100] = "EPROTO",
                      [101] = "ETIME",
                      [102] = "EOPNOTSUPP",
                      [103] = "ENOPOLICY",
                      [104] = "ENOTRECOVERABLE",
                      [105] = "EOWNERDEAD",
                      [106] = "EQFULL",
                      [106] = "ELAST",
}, { __index = function(key) return tostring(key) end })
